<a href="https://colab.research.google.com/github/nivethithanm/torchcode-solutions/blob/main/B_03_causal_mask.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# B-03: Causal Mask Construction

**Difficulty**: 🟢 Easy | **Bridges**: Masking → Causal Attention

In [1]:
import torch

## Task 1: Standard Causal Mask

In [3]:
def make_causal_mask(N):
    """Create an NxN causal (lower triangular) boolean mask.
    mask[i,j] = True if j <= i (can attend to past and self)
    """
    # TODO: Implement
    mask = torch.tril(torch.ones(N, N)).bool()
    return mask

mask = make_causal_mask(5)
print(mask.int())
assert mask[0, 0] == True   # can attend to self
assert mask[0, 1] == False  # can't attend to future
assert mask[4, 0] == True   # can attend to all past
print('✅ Task 1 passed!')

tensor([[1, 0, 0, 0, 0],
        [1, 1, 0, 0, 0],
        [1, 1, 1, 0, 0],
        [1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1]], dtype=torch.int32)
✅ Task 1 passed!


## Task 2: Sliding Window Causal Mask

In [6]:
torch.arange(6).view(-1, 1)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5]])

In [7]:
def make_sliding_window_mask(N, window_size):
    """Causal mask that only attends to the last `window_size` tokens.
    mask[i,j] = True if (j <= i) AND (i - j < window_size)
    """
    # TODO: Implement
    row_idx = torch.arange(N).unsqueeze(1)
    col_idx = torch.arange(N).unsqueeze(0)
    is_causal = col_idx <= row_idx
    is_within_window = (row_idx - col_idx) < window_size
    mask = is_causal & is_within_window
    return mask

mask = make_sliding_window_mask(6, 3)
print(mask.int())
# Row 5 should only attend to positions 3, 4, 5
assert mask[5, 2] == False
assert mask[5, 3] == True
print('✅ Task 2 passed!')

tensor([[1, 0, 0, 0, 0, 0],
        [1, 1, 0, 0, 0, 0],
        [1, 1, 1, 0, 0, 0],
        [0, 1, 1, 1, 0, 0],
        [0, 0, 1, 1, 1, 0],
        [0, 0, 0, 1, 1, 1]], dtype=torch.int32)
✅ Task 2 passed!
